import React, { Component} from 'react';
import './app.css';
const myNews=[{id:"1",name:"Продукт 1",price:"1111200",text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",image:"samovar1.jpg"},{id:"2",name:"Продукт 2",price:"1400",text:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",image:"samovar2.jpg"},{id:"3",name:"Продукт 3",price:"1600",text:"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",image:"samovar3.jpg"}];
function Btn_add ({ price, add }) {const [isPress, setIsPress] = React.useState(false);const onClAdd = () => {setIsPress(!isPress);add(isPress ? -price : price);}
return (<div><button onClick={() => onClAdd()} className="card__button text-center boldUp" disabled={isPress ? true : false}>{isPress ? "Добавлено" : "Добавить в корзину"}</button></div>)};
const ReplacePrice=d=>d.toString().replace(/(\d{1,3}(?=(?:\d\d\d)+(?!\d)))/g,"$1 ");
const ColContent=({name,price,text,img,add})=>{return (<div className="wrapper col-12 col-md-6 col-lg-4"><div className="card"><h2 className="card__title text-center mb-2">{name}</h2> <img className="card__img center mb-3" src={img} alt="img"></img><p className="mb-0">{text}</p><div><h3 className="card__price boldUp text-center mb-0 ">{ReplacePrice(price)} руб.</h3></div><Btn_add price={price} add={add} /></div></div>)};
function ShopList () {const [listPrice, setListPrice] = React.useState(0);const addPrice = (obj) => {setListPrice((parseInt(listPrice) + parseInt(obj)));} 
return (<div className="blockM"><h2 className="blockM__title boldUp text-center mb-3">Заголовок блока</h2><h3 className="blockM__title_lower text-center mb-5">Подзаголовок блока</h3><div className="container mb-5"><div className="row">{myNews.map((obj) => (<ColContent key={obj.id} name={obj.name} price={obj.price} text={obj.text} img={obj.image} add={addPrice}/>))}</div></div><div className="blockM__text"><p className="blockM__text_name container">ОБЩАЯ СУММА: <span className="blockM__text_price">{ReplacePrice(listPrice)}</span> руб.</p></div></div>);};
export default class App extends Component {render() {return (<div><ShopList /></div>);}};